# yaml-language-server: $schema=https://raw.githubusercontent.com/EnterpriseDB/docs/refs/heads/develop/tools/automation/generators/relgen/meta-schema.json

product: EDB Stat Monitor
shortname: edb_stat_monitor
title: EDB Stat Monitor (edb_stat_monitor) release notes
description: Release notes for EDB Stat Monitor releases
columns:
- 0:
  label: "edb_stat_monitor version"
  key: version-link
- 1:
  label: Release Date
  key: shortdate
intro: |
  The EDB Stat Monitor documentation describes the latest version of EDB Stat Monitor.
