product: EDB Postgres AI - AI Accelerator
shortname: ai-accelerator
title: EDB Postgres AI - AI Accelerator 1.0.0 release notes
description: Release notes for EDB Postgres AI - AI Accelerator 1.0.0
intro: |
  The EDB Postgres AI - AI Accelerator describes the latest version of AI Accelerator. The release notes provide information on what was new in each release. For the GA 1.0.0 release, differences from the technical preview are highlighted.
columns:
- 0:
  label: "AI Accelerator version"
  key: version-link
- 1:
  label: Release Date
  key: shortdate
