product: EDB Postgres AI - AI Accelerator
shortname: ai-accelerator
title: EDB Postgres AI - AI Accelerator release notes
description: Release notes for EDB Postgres AI - AI Accelerator
intro: |
  The EDB Postgres AI - AI Accelerator describes the latest version of AI Accelerator. The release notes provide information on what was new in each release. Differences from the technical preview are highlighted in the 1.0.7 release notes.
columns:
- 0:
  label: "AI Accelerator version"
  key: version-link
- 1:
  label: Release Date
  key: shortdate
