[context.production]
     GATSBY_ENVIRONMENT_BRANCH = "main"

 [context.deploy-preview.environment]
     GATSBY_ENVIRONMENT_BRANCH = "develop"

 [context.branch-deploy]
     GATSBY_ENVIRONMENT_BRANCH = "develop"
