# yaml-language-server: $schema=https://raw.githubusercontent.com/EnterpriseDB/docs/develop/tools/automation/generators/relgen/meta-schema.json
product: EDB Postgres® AI for CloudNativePG™ Global Cluster
shortname: ""
title: EDB Postgres® AI for CloudNativePG™ Global Cluster release notes
description: Release notes for EDB Postgres® AI for CloudNativePG™ Global Cluster
intro: |
  The EDB Postgres Distributed for Kubernetes documentation describes the major version of EDB Postgres Distributed for Kubernetes, 
  including minor releases and patches. The release notes provide information on what is new in each release. For new functionality 
  introduced in a minor or patch release, the content also indicates the release that introduced the feature.
frontmatter:
  redirects:
    - ../release_notes
columns:
- 0:
  label: "Version"
  key: version-link
- 1:
  label: Release date
  key: shortdate
precursor:
- date: 18 Mar 2025  
  version: 1.1.1
- date: 25 Dec 2024  
  version: 1.1.0
- date: 14 Oct 2024  
  version: 1.0.1
- date: 24 Apr 2024  
  version: 1.0.0
