apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: ImageCatalog
metadata:
  name: image-catalog-example
spec:
  images:
    - image: docker.enterprisedb.com/k8s/postgresql:18-standard-ubi9
      major: 18
    - image: docker.enterprisedb.com/k8s/postgresql:17-standard-ubi9
      major: 17
    - image: docker.enterprisedb.com/k8s/postgresql:16-standard-ubi9
      major: 16
    - image: docker.enterprisedb.com/k8s/postgresql:15-standard-ubi9
      major: 15
---
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  imageCatalogRef:
    apiGroup: postgresql.k8s.enterprisedb.io
    kind: ImageCatalog
    name: image-catalog-example
    major: 15
  storage:
    size: 1Gi
