apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: additional-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-example
  annotations:
    k8s.enterprisedb.io/additionalVolumes: |
      - claimName: additional-pvc
        readOnly: true
        mountPath: /additional
spec:
  instances: 1
  storage:
    size: 1Gi
