apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  instances: 3
  # imageName: docker-epas:13

  bootstrap:
    initdb:
      redwood: false

  storage:
    size: 1Gi
