
services:
  host-1:
    hostname: host-1
    image: pgd
    environment:
      PGPASSWORD: secret
      PGD_JOIN_NODE_DSN: "port=5432 dbname=pgddb host=host-1 user=postgres"
    restart: always
    volumes:
      - ./host-1-data:/var/lib/postgresql/data

  host-2:
    hostname: host-2
    extends: host-1
    volumes:
     - ./host-2-data:/var/lib/postgresql/data

  host-3:
    hostname:  host-3
    extends: host-1
    volumes:
     - ./host-3-data:/var/lib/postgresql/data

