# yaml-language-server: $schema=https://raw.githubusercontent.com/EnterpriseDB/docs/refs/heads/develop/tools/automation/generators/relgen/meta-schema.json
product: LiveCompare
shortname: livecompare
title: LiveCompare release notes
description: Release notes for LiveCompare 3 and later
columns:
- 0:
  label: "LiveCompare version"
  key: version-link
- 1:
  label: Release Date
  key: shortdate
intro: |
  The LiveCompare documentation describes the latest version of LiveCompare 3.
precursor:
- version: "3.0.2"
  date:  21 Nov 2024
- version: "3.0.1"
  date:  30 Sep 2024