@startuml


!pragma revision 1

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureSimplified.puml
!includeurl AzurePuml/Databases/AzureDatabaseForPostgreSQL.puml
!includeurl AzurePuml/Networking/AzureLoadBalancer.puml
!includeurl AzurePuml/Web/AzureWebApp.puml


AzureWebApp(app1, "App","")
AzureWebApp(app2, "App","")
AzureWebApp(app3, "App","")
rectangle "EDB Cloud cluster" as src {
   AzureLoadBalancer(service, "Service", "")
   AzureDatabaseForPostgreSQL(primary,"PostgreSQL Primary", "Primary"   )
   AzureDatabaseForPostgreSQL(standby1, "PostgreSQL Standby", "Standby"   )
   AzureDatabaseForPostgreSQL(standby2, "PostgreSQL Standby", "Standby"   )

   primary -> standby1
   primary  -> standby2
   service <-d->primary
}

app1-d->service
app2-d->service
app3-d->service
@enduml
