# yaml-language-server: $schema=https://raw.githubusercontent.com/EnterpriseDB/docs/refs/heads/develop/tools/automation/generators/relgen/meta-schema.json

product: EDB Postgres Distributed
shortname: pgd
title: EDB Postgres Distributed 6 release notes
description: Release notes for EDB Postgres Distributed 6 and later
intro: |
  The EDB Postgres Distributed documentation describes the latest version of EDB Postgres Distributed 6, including minor releases and patches. The release notes provide information on what was new in each release. For new functionality introduced in a minor or patch release, the content also indicates the release that introduced the feature.
columns:
- 0:
  label: Release Date
  key: shortdate
- 1:
  label: "EDB Postgres Distributed"
  key: version-link
- 2:
  label: "BDR extension"
  key: "$BDR"
- 3:
  label: "PGD CLI"
  key: "$PGD CLI"
components: [ "BDR", "PGD CLI", "Utilities" ]
