@startuml

!pragma ratio 1
!pragma revision 1


!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

!define AzurePuml https://raw.githubusercontent.com/plantuml-stdlib/Azure-PlantUML/master/dist
!includeurl AzurePuml/AzureCommon.puml
!includeurl AzurePuml/AzureSimplified.puml
!includeurl AzurePuml/Databases/AzureDatabaseForPostgreSQL.puml
!includeurl AzurePuml/Identity/AzureActiveDirectoryB2C.puml
!includeurl AzurePuml/Identity/AzureActiveDirectoryDomainServices.puml
left to right direction


rectangle "EDB Cloud" as src {
  rectangle "EDB Cloud Clusters" as edbclusters {
   AzureDatabaseForPostgreSQL(edbcl1, "PG Cluster","DB cluster1" )
   AzureDatabaseForPostgreSQL(edbcl2, "EPAS Cluster","DB cluster2" )

  }

  rectangle "EDB Cloud Users" {
    Person(tom2, "Tom:{reader}")
    Person(jerry2, "Jerry:{owner}")

  }


  AzureActiveDirectoryB2C(org, "EDB Cloud Organization ", "org acmebank-com")

}

rectangle Azure as tgt {

  rectangle "Azure AD Members" {
      Person(tom, "Tom")
      Person(jerry, "Jerry")

    }

  rectangle "Regions" as regions {
    rectangle "us-east" as k1 {
     AzureDatabaseForPostgreSQL(azuredbcl1, "PG Cluster","DB cluster1" )

    }
    rectangle "japan-west" as k2 {
       AzureDatabaseForPostgreSQL(azuredbcl2, "EPAS Cluster","DB cluster2" )
    }
  }

  AzureActiveDirectoryDomainServices(AD, "Azure AD Tenant", "tenant acmebank.com")

}
jerry -> regions: owns
src -[hidden]d-> tgt
regions -[hidden]u-> edbclusters
org  <->  AD: "1:1"
tom2<- tom
jerry2<- jerry



edbcl1 <- azuredbcl1
edbcl2 <- azuredbcl2
@enduml
