# This file is intended for development only.
# It will allow users to quickly get this app running so that they can start making updates without worrying about
# whether or not dependencies are properly installed.
FROM node:14-alpine

RUN apk update && apk --no-cache add build-base autoconf automake libtool pkgconfig nasm

RUN npm install -g npm@7

WORKDIR /home/app

CMD npm run install-dependencies && npm run develop -- -H 0.0.0.0 -p ${PORT:-8000} 2>&1
