FROM node:18-alpine as base

RUN npm install -g npm@9
WORKDIR /app


FROM base as dependencies

COPY install_template/package*.json ./
RUN npm i


FROM base as renderer

COPY --from=dependencies /app/node_modules /app/node_modules
