FROM node:14-alpine as base

RUN apk update && apk --no-cache add util-linux
RUN npm install -g npm@7
WORKDIR /app
COPY . .


FROM base as dependencies

RUN apk update && apk --no-cache add \
  autoconf \
  automake \
  build-base \
  libtool \
  nasm \
  pkgconfig

ARG NPM_TOKEN
RUN npm run preinstall --if-present
RUN scripts/npm-install.sh


FROM base as dev-server

COPY --from=dependencies /app/node_modules /app/node_modules
