FROM node:22-alpine as base

WORKDIR /app


FROM base as dependencies

COPY install_template/package*.json ./
RUN npm i


FROM base as renderer

COPY --from=dependencies /app/node_modules /app/node_modules
