product: Trusted Postgres Architect
shortname: tpa
title: Trusted Postgres Architect release notes
description: Release notes for Trusted Postgres Architect and later
columns:
- 0:
  label: "Trusted Postgres Architect version"
  key: version-link
- 1:
  label: Release Date
  key: shortdate
intro: |
  The Trusted Postgres Architect documentation describes the latest version of Trusted Postgres Architect 23.
precursor:
- version: "23.34.1"
  date:  09 Sep 2024
- version: "23.34"
  date:  22 Aug 2024
- version: "23.33"
  date:  24 Jun 2024
- version: "23.32"
  date:  15 May 2024
- version: "23.31"
  date:  19 Mar 2024
- version: "23.30"
  date:  19 Mar 2024
- version: "23.29"
  date:  15 Feb 2024
- version: "23.28"
  date:  23 Jan 2024
- version: "23.27"
  date:  19 Dec 2023
- version: "23.26"
  date:  30 Nov 2023
- version: "23.25"
  date:  14 Nov 2023
- version: "23.24"
  date:  17 Oct 2023
- version: "23.23"
  date:  21 Sep 2023
- version: "23.22"
  date:  06 Sep 2023
- version: "23.21"
  date:  05 Sep 2023
- version: "23.20"
  date:  01 Aug 2023
- version: "23.19"
  date:  12 Jul 2023
- version: "23.18"
  date:  23 May 2023
- version: "23.17"
  date:  10 May 2023
- version: "23.16"
  date:  21 Mar 2023
- version: "23.15"
  date:  15 Mar 2023
- version: "23.14"
  date:  23 Feb 2023
- version: "23.13"
  date:  22 Feb 2023
- version: "23.12"
  date:  21 Feb 2023
- version: "23.1-11"
  date:  21 Jun 2023 to 31 Jan 2023

