name: Problem with a topic
description: Report a problem you've observed while reading a topic
title: "Problem on (PUT PAGE PATH / URL / TITLE HERE)"
body: 
- type: textarea
  attributes:
    label: Summary
    description: >
      A short description of the problem you observed. Ex: "Code sample fails with error", "Link is broken"
  validations:
    required: false
- type: textarea
  id: context
  attributes:
    label: Where did you see the problem?
    description: |
      Please link to the topic on the EDB website or file on GitHub where you observed the problem.
      Also, describe the location within the text. 

      Example: 

      > https://www.enterprisedb.com/docs/postgres_for_kubernetes/latest/troubleshooting/#storage-is-full 
      >
      > in the section titled 'Storage is full', the first link doesn't load"
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: >
      Describe what you expected, changes you'd like to see, etc.
  validations:
    required: false
- type: textarea
  attributes:
    label: Screenshots
    description: >
      If applicable, paste / upload screenshots to illustrate the problem you saw
  validations:
    required: false
- type: textarea
  attributes:
    label: Browser / Platform
    description: >
      Include the name of the browser and operating system you were using, along with versions
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional notes
    description: >
      Anything else you'd like to add that might help us to fix the problem
  validations:
    required: false

