name: Product Feedback
description: Share feedback regarding an EDB product
body: 
- type: markdown
  attributes:
    value: |
      If you have questions or feedback regarding the use of an EDB product, the best way to 
      get help is our Knowledge Base: https://support.enterprisedb.com/support/s/
      There you can review existing topics and open a case with our support team.

      If you have feedback related to how the product is documented, please provide details below!  
- type: textarea
  id: context
  attributes:
    label: What topic do you have feedback on?
    description: >
      Please link to the relevant topic on the EDB website or file on GitHub
  validations:
    required: true
- type: textarea
  attributes:
    label: Your feedback
  validations:
    required: false

