---
name: Propose a new topic
description: Suggest the addition of a new page or section
labels: "enhancement"
body: 
- type: textarea
  attributes:
    label: Summary
    description: |
      A short description of what you'd like to see covered. 

      Example:

      > Advanced Server examples could use more waffle recipies
  validations:
    required: false
- type: textarea
  attributes:
    label: Background info
    description: |
      What do you already know about the topic? What would you like to learn? What sort of things will this information help you to do?

      (If you're proposing this topic because you think it would benefit _someone else_, then summarize _their_ background knowledge and needs)
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional notes
    description: >
      Anything else you'd like to add
  validations:
    required: false


