name: Suggest an addition
description: Suggest an improvement to a topic
title: "Idea for (PUT PAGE PATH / URL / TITLE HERE)"
labels: "enhancement"
body: 
- type: textarea
  attributes:
    label: Summary
    description: >
      A short description of what you'd like to see. Ex: "An example using a Lateral Join would be nice"
  validations:
    required: false
- type: textarea
  id: context
  attributes:
    label: Where would you like to see this added?
    description: |
      Please link to the topic on the EDB website or file on GitHub that you'd like to see updated.
      If relevant, also describe the location within the page's text that would be improved by addition.

      Example:

      > https://www.enterprisedb.com/docs/epas/latest/
      >
      > It would be nice to have a link to the edb-psql topic under "tools"
  validations:
    required: true
- type: textarea
  attributes:
    label: Rationale
    description: |
      Why you'd like to see this addition. Be detailed! 

      Example: 
      
      > Results currently require post-processing to bring in contextual info; the use of a lateral join to perform this step would simplify the example while demonstrating a pure-SQL solution
  validations:
    required: false
