name: There is a typo (or minor mistake)
description: Report a small problem you've observed while reading a topic
title: "Problem on (PUT PAGE PATH / URL / TITLE HERE)"
body: 
- type: textarea
  id: context
  attributes:
    label: What topic is affected?
    description: >
      Please link to the topic on the EDB website or file on GitHub where you found the mistake
  validations:
    required: true
- type: textarea
  attributes:
    label: What was the typo or mistake?
    description: >
      A short description of the problem you observed. Ex: "thier is a misspelling", "https://grogle.com/search is broken"
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional information
    description: >
      Add any other relevant information, context or screenshots here 
  validations:
    required: false
