version: "3.8"

services:
  docs-dev-server:
    build:
      context: ../
      dockerfile: docker/images/Dockerfile.quickstart
      args:
        - NPM_TOKEN
    image: edb/docs-dev-server
    container_name: docs-dev-server
    hostname: docs-dev-server
    env_file:
      - ../.env.development
    init: true
    command: >
      sh -c "npm run preinstall --if-present &&
      scripts/npm-install.sh &&
      npm run develop -- -H 0.0.0.0 -p ${PORT:-8000} 2>&1"
    ports:
      - ${PORT:-8000}:${PORT:-8000}
    volumes:
      - ../advocacy_docs:/app/advocacy_docs:ro
      - ../product_docs:/app/product_docs:ro
      - ../scripts:/app/scripts:ro
      - ../src:/app/src:ro
      - ../static:/app/static:ro
      - gatsby-cache:/app/.cache
      - gatsby-public:/app/public

volumes:
  gatsby-cache:
  gatsby-public:
