# Vagrantfile
etcd_nodes = 3 # nb of etcd nodes to create
patroni_nodes = 2 # nb of pg/patroni nodes to create

Vagrant.configure(2) do |config|
    config.vm.box = 'rockylinux/8'
    config.vm.provider 'libvirt' do |lv|
        lv.cpus = 1
        lv.memory = 1024
        lv.default_prefix = 'rocky8'
        lv.machine_virtual_size = 30
    end
    config.vm.synced_folder ".", "/vagrant", disabled: true

    (1..etcd_nodes).each do |i|
        config.vm.define "etcd#{i}" do |etcd|
            etcd.vm.hostname = "etcd#{i}"
        end  
    end

    (1..patroni_nodes).each do |i|
        config.vm.define "epas-patroni#{i}" do |patroni|
            patroni.vm.hostname = "epas-patroni#{i}"
        end
    end

    (1..patroni_nodes).each do |i|
        config.vm.define "pgext-patroni#{i}" do |patroni|
            patroni.vm.hostname = "pgext-patroni#{i}"
        end
    end

    config.vm.provision "shell", inline: <<-SHELL
        #-----------------------------------------------------------------------------------------------------------------------
        sudo dnf install -y cloud-utils-growpart
        sudo growpart /dev/vda 1
        sudo xfs_growfs /dev/vda1
        sudo dnf update -y libmodulemd
        sudo dnf install -y bind-utils
        sudo systemctl start firewalld
        sudo systemctl enable firewalld
        #-----------------------------------------------------------------------------------------------------------------------
    SHELL
end
