# yaml-language-server: $schema=https://raw.githubusercontent.com/EnterpriseDB/docs/automation/josh/validation-for-relgen/tools/automation/generators/relgen/meta-schema.json
product: EDB CloudNativePG Cluster
shortname: ""
title: EDB CloudNativePG Cluster release notes
description: Release notes for EDB CloudNativePG Cluster
intro: |
  The EDB Postgres for Kubernetes documentation describes the major version of EDB Postgres for Kubernetes, including minor releases and patches. The release notes provide information on what is new in each release. For new functionality introduced in a minor or patch release, the content also indicates the release that introduced the feature.
outro: |
  !!! Info Versions prior to 1.0.0
      EDB Postgres for Kubernetes was made generally available on February 4, 2021. 
      Earlier versions were made available to selected customers prior to the GA release.
frontmatter:
  redirects:
    - ../release_notes
columns:
- 0:
  label: "Version"
  key: version-link
- 1:
  label: Release date
  key: shortdate
- 2:
  label: Upstream merges
  key: $upstream-merge
precursor:
- date: 04 Mar 2025  
  version: 1.25.1
  upstream-merge:  Upstream [1.25.1](https://cloudnative-pg.io/documentation/1.25/release_notes/v1.25/)
- date: 23 Dec 2025  
  version: 1.25.0
  upstream-merge:  Upstream [1.25.0](https://cloudnative-pg.io/documentation/1.25/release_notes/v1.25/)
- date: 04 Mar 2025  
  version: 1.24.3
  upstream-merge:  Upstream [1.24.3](https://cloudnative-pg.io/documentation/1.24/release_notes/v1.24/)
- date: 23 Dec 2024  
  version: 1.24.2
  upstream-merge:  Upstream [1.24.2](https://cloudnative-pg.io/documentation/1.24/release_notes/v1.24/)
- date: 18 Oct 2024  
  version: 1.24.1
  upstream-merge:  Upstream [1.24.1](https://cloudnative-pg.io/documentation/1.24/release_notes/v1.24/)
- date: 26 Aug 2024  
  version: 1.24.0
  upstream-merge:  Upstream [1.24.0](https://cloudnative-pg.io/documentation/1.24/release_notes/v1.24/)
- date: 23 Dec 2024  
  version: 1.23.6
  upstream-merge:  Upstream [1.23.6](https://cloudnative-pg.io/documentation/1.23/release_notes/v1.23/)
- date: 18 Oct 2024  
  version: 1.23.5
  upstream-merge:  Upstream [1.23.5](https://cloudnative-pg.io/documentation/1.23/release_notes/v1.23/)
- date: 26 Aug 2024  
  version: 1.23.4
  upstream-merge:  Upstream [1.23.4](https://cloudnative-pg.io/documentation/1.23/release_notes/v1.23/)
- date: 01 Aug 2024  
  version: 1.23.3
  upstream-merge:  Upstream [1.23.3](https://cloudnative-pg.io/documentation/1.23/release_notes/v1.23/)
- date: 13 Jun 2024  
  version: 1.23.2
  upstream-merge:  Upstream [1.23.2](https://cloudnative-pg.io/documentation/1.23/release_notes/v1.23/)
- date: 29 Apr 2024  
  version: 1.23.1
  upstream-merge:  Upstream [1.23.1](https://cloudnative-pg.io/documentation/1.23/release_notes/v1.23/)
- date: 24 Apr 2024  
  version: 1.23.0
  upstream-merge:  Upstream [1.23.0](https://cloudnative-pg.io/documentation/1.23/release_notes/v1.23/)
- date: 04 Mar 2025  
  version: 1.22.9
  upstream-merge:  None
- date: 23 Dec 2024  
  version: 1.22.8
  upstream-merge:  None
- date: 18 Oct 2024  
  version: 1.22.7
  upstream-merge:  None
- date: 26 Aug 2024  
  version: 1.22.6
  upstream-merge:  Upstream [1.22.6](https://cloudnative-pg.io/documentation/1.22/release_notes/v1.22/)
- date: 01 Aug 2024  
  version: 1.22.5
  upstream-merge:  Upstream [1.22.5](https://cloudnative-pg.io/documentation/1.22/release_notes/v1.22/)
- date: 13 Jun 2024  
  version: 1.22.4
  upstream-merge:  Upstream [1.22.4](https://cloudnative-pg.io/documentation/1.22/release_notes/v1.22/)
- date: 24 Apr 2024  
  version: 1.22.3
  upstream-merge:  Upstream [1.22.3](https://cloudnative-pg.io/documentation/1.22/release_notes/v1.22/)
- date: 22 Mar 2024  
  version: 1.22.2
  upstream-merge:  Upstream [1.22.2](https://cloudnative-pg.io/documentation/1.22/release_notes/v1.22/)
- date: 02 Feb 2024  
  version: 1.22.1
  upstream-merge:  Upstream [1.22.1](https://cloudnative-pg.io/documentation/1.22/release_notes/v1.22/)
- date: 22 Dec 2023  
  version: 1.22.0
  upstream-merge:  Upstream [1.22.0](https://cloudnative-pg.io/documentation/1.22/release_notes/v1.22/)
- date: 13 Jun 2024  
  version: 1.21.6
  upstream-merge:  Upstream [1.21.6](https://cloudnative-pg.io/documentation/1.21/release_notes/v1.21/)
- date: 24 Apr 2024  
  version: 1.21.5
  upstream-merge:  Upstream [1.21.5](https://cloudnative-pg.io/documentation/1.21/release_notes/v1.21/)
- date: 22 Mar 2024  
  version: 1.21.4
  upstream-merge:  Upstream [1.21.4](https://cloudnative-pg.io/documentation/1.21/release_notes/v1.21/)
- date: 02 Feb 2024  
  version: 1.21.3
  upstream-merge:  Upstream [1.21.3](https://cloudnative-pg.io/documentation/1.21/release_notes/v1.21/)
- date: 22 Dec 2023  
  version: 1.21.2
  upstream-merge:  Upstream [1.21.2](https://cloudnative-pg.io/documentation/1.21/release_notes/v1.21/)
- date: 08 Nov 2023  
  version: 1.21.1
  upstream-merge:  Upstream [1.21.1](https://cloudnative-pg.io/documentation/1.21/release_notes/v1.21/)
- date: 18 Oct 2023  
  version: 1.21.0
  upstream-merge:  Upstream [1.21.0](https://cloudnative-pg.io/documentation/1.21/release_notes/v1.21/)
- date: 02 Feb 2024  
  version: 1.20.6
  upstream-merge:  Upstream [1.20.6](https://cloudnative-pg.io/documentation/1.20/release_notes/v1.20/)
- date: 22 Dec 2023  
  version: 1.20.5
  upstream-merge:  Upstream [1.20.5](https://cloudnative-pg.io/documentation/1.20/release_notes/v1.20/)
- date: 08 Nov 2023  
  version: 1.20.4
  upstream-merge:  Upstream [1.20.4](https://cloudnative-pg.io/documentation/1.20/release_notes/v1.20/)
- date: 18 Oct 2023  
  version: 1.20.3
  upstream-merge:  Upstream [1.20.3](https://cloudnative-pg.io/documentation/1.20/release_notes/v1.20/)
- date: 27 Jul 2023  
  version: 1.20.2
  upstream-merge:  Upstream [1.20.2](https://cloudnative-pg.io/documentation/1.20/release_notes/v1.20/)
- date: 13 Jun 2023  
  version: 1.20.1
  upstream-merge:  Upstream [1.20.1](https://cloudnative-pg.io/documentation/1.20/release_notes/v1.20/)
- date: 27 Apr 2023  
  version: 1.20.0
  upstream-merge:  Upstream [1.20.0](https://cloudnative-pg.io/documentation/1.20/release_notes/v1.20/)
- date: 08 Nov 2023  
  version: 1.19.6
  upstream-merge:  Upstream [1.19.6](https://cloudnative-pg.io/documentation/1.19/release_notes/v1.19/)
- date: 18 Oct 2023  
  version: 1.19.5
  upstream-merge:  Upstream [1.19.5](https://cloudnative-pg.io/documentation/1.19/release_notes/v1.19/)
- date: 27 Jul 2023  
  version: 1.19.4
  upstream-merge:  Upstream [1.19.4](https://cloudnative-pg.io/documentation/1.19/release_notes/v1.19/)
- date: 13 Jun 2023  
  version: 1.19.3
  upstream-merge:  Upstream [1.19.3](https://cloudnative-pg.io/documentation/1.19/release_notes/v1.19/)
- date: 27 Apr 2023  
  version: 1.19.2
  upstream-merge:  Upstream [1.19.2](https://cloudnative-pg.io/documentation/1.19/release_notes/v1.19/)
- date: 20 Mar 2023  
  version: 1.19.1
  upstream-merge:  Upstream [1.19.1](https://cloudnative-pg.io/documentation/1.19/release_notes/v1.19/)
- date: 14 Feb 2023  
  version: 1.19.0
  upstream-merge:  Upstream [1.19.0](https://cloudnative-pg.io/documentation/1.19/release_notes/v1.19/)
- date: 13 Jun 2024 
  version: 1.18.13
  upstream-merge:  None
- date: 24 Apr 2024 
  version: 1.18.12
  upstream-merge:  None
- date: 22 Mar 2024 
  version: 1.18.11
  upstream-merge:  None
- date: 02 Feb 2024 
  version: 1.18.10
  upstream-merge:  None
- date: 22 Dec 2023 
  version: 1.18.9
  upstream-merge:  None
- date: 08 Nov 2023 
  version: 1.18.8
  upstream-merge:  None
- date: 18 Oct 2023 
  version: 1.18.7
  upstream-merge:  None
- date: 27 Jul 2023 
  version: 1.18.6
  upstream-merge:  None
- date: 13 Jun 2023 
  version: 1.18.5
  upstream-merge:  Upstream [1.18.5](https://cloudnative-pg.io/documentation/1.18/release_notes/v1.18/)
- date: 27 Apr 2023 
  version: 1.18.4
  upstream-merge:  Upstream [1.18.4](https://cloudnative-pg.io/documentation/1.18/release_notes/v1.18/)
- date: 20 Mar 2023  
  version: 1.18.3
  upstream-merge:  Upstream [1.18.3](https://cloudnative-pg.io/documentation/1.18/release_notes/v1.18/)
- date: 14 Feb 2023  
  version: 1.18.2
  upstream-merge:  Upstream [1.18.2](https://cloudnative-pg.io/documentation/1.18/release_notes/v1.18/)
- date: 21 Dec 2022  
  version: 1.18.1
  upstream-merge:  Upstream [1.18.1](https://cloudnative-pg.io/documentation/1.18/release_notes/v1.18/)
- date: 14 Nov 2022  
  version: 1.18.0
  upstream-merge:  Upstream [1.18.0](https://cloudnative-pg.io/documentation/1.18/release_notes/v1.18/)
- date: 20 Mar 2023  
  version: 1.17.5
  upstream-merge:  Upstream [1.17.5](https://cloudnative-pg.io/documentation/1.17/release_notes/v1.17/)
- date: 14 Feb 2023  
  version: 1.17.4
  upstream-merge:  Upstream [1.17.4](https://cloudnative-pg.io/documentation/1.17/release_notes/v1.17/)
- date: 21 Dec 2022  
  version: 1.17.3
  upstream-merge:  Upstream [1.17.3](https://cloudnative-pg.io/documentation/1.17/release_notes/v1.17/)
- date: 14 Nov 2022  
  version: 1.17.2
  upstream-merge:  Upstream [1.17.2](https://cloudnative-pg.io/documentation/1.17/release_notes/v1.17/)
- date: 07 Oct 2022  
  version: 1.17.1
  upstream-merge:  Upstream [1.17.1](https://cloudnative-pg.io/documentation/1.17/release_notes/v1.17/)
- date: 06 Sep 2022  
  version: 1.17.0
  upstream-merge:  Upstream [1.17.0](https://cloudnative-pg.io/documentation/1.17/release_notes/v1.17/)
- date: 21 Dec 2022 
  version: 1.16.5
  upstream-merge:  Upstream [1.16.4](https://cloudnative-pg.io/documentation/1.16/release_notes/v1.16/)
- date: 14 Nov 2022 
  version: 1.16.4
  upstream-merge:  Upstream [1.16.4](https://cloudnative-pg.io/documentation/1.16/release_notes/v1.16/)
- date: 07 Oct 2022  
  version: 1.16.3
  upstream-merge:  Upstream [1.16.3](https://cloudnative-pg.io/documentation/1.16/release_notes/v1.16/)
- date: 06 Sep 2022  
  version: 1.16.2
  upstream-merge:  Upstream [1.16.2](https://cloudnative-pg.io/documentation/1.16/release_notes/v1.16/)
- date: 12 Aug 2022 
  version: 1.16.1
  upstream-merge:  Upstream [1.16.1](https://cloudnative-pg.io/documentation/1.16/release_notes/v1.16/)
- date: 07 Jul 2022 
  version: 1.16.0
  upstream-merge:  Upstream [1.16.0](https://cloudnative-pg.io/documentation/1.16/release_notes/v1.16)
- date: 07 Oct 2022  
  version: 1.15.5
  upstream-merge:  Upstream [1.15.5](https://cloudnative-pg.io/documentation/1.15/release_notes/v1.15)
- date: 06 Sep 2022  
  version: 1.15.4
  upstream-merge:  Upstream [1.15.4](https://cloudnative-pg.io/documentation/1.15/release_notes/v1.15)
- date: 12 Aug 2022 
  version: 1.15.3
  upstream-merge:  Upstream [1.15.3](https://cloudnative-pg.io/documentation/1.15/release_notes/v1.15)
- date: 07 Jul 2022 
  version: 1.15.2
  upstream-merge:  Upstream [1.15.2](https://cloudnative-pg.io/documentation/1.15/release_notes/v1.15)
- date: 27 May 2022 
  version: 1.15.1
  upstream-merge:  Upstream [1.15.1](https://cloudnative-pg.io/documentation/1.15/release_notes/v1.15)
- date: 21 Apr 2022 
  version: 1.15.0
  upstream-merge:  Upstream [1.15.0](https://cloudnative-pg.io/documentation/1.15/release_notes/v1.15)
- date: 25 Mar 2022 
  version: 1.14.0
  upstream-merge:  NA                                                                                         
- date: 17 Feb 2022 
  version: 1.13.0
  upstream-merge:  NA                                                                                         
- date: 11 Jan 2022 
  version: 1.12.0
  upstream-merge:  NA                                                                                         
- date: 15 Dec 2021 
  version: 1.11.0
  upstream-merge:  NA                                                                                         
- date: 11 Nov 2021 
  version: 1.10.0
  upstream-merge:  NA                                                                                         
- date: 15 Oct 2021 
  version: 1.9.2
  upstream-merge:  NA                                                                                         
- date: 30 Sep 2021 
  version: 1.9.1
  upstream-merge:  NA                                                                                         
- date: 28 Sep 2021 
  version: 1.9.0
  upstream-merge:  NA                                                                                         
- date: 13 Sep 2021 
  version: 1.8.0
  upstream-merge:  NA                                                                                         
- date: 11 Aug 2021 
  version: 1.7.1
  upstream-merge:  NA                                                                                         
- date: 28 Jul 2021 
  version: 1.7.0
  upstream-merge:  NA                                                                                         
- date: 12 Jul 2021 
  version: 1.6.0
  upstream-merge:  NA                                                                                         
- date: 11 Jun 2021 
  version: 1.5.1
  upstream-merge:  NA                                                                                         
- date: 17 Jun 2021 
  version: 1.5.0
  upstream-merge:  NA                                                                                         
- date: 18 May 2021 
  version: 1.4.0
  upstream-merge:  NA                                                                                         
- date: 23 Apr 2021 
  version: 1.3.0
  upstream-merge:  NA                                                                                         
- date: 06 Apr 2021 
  version: 1.2.1
  upstream-merge:  NA                                                                                         
- date: 31 Mar 2021 
  version: 1.2.0
  upstream-merge:  NA                                                                                         
- date: 03 Mar 2021 
  version: 1.1.0
  upstream-merge:  NA                                                                                         
- date: 04 Feb 2021
  version: "1.0.0"
  upstream-merge: NA
- date: 29 Jan 2021
  version: "0.8.0"
  upstream-merge: NA
- date: 31 Dec 2020
  version: "0.7.0"
  upstream-merge: NA
- date: 04 Dec 2020
  version: "0.6.0"
  upstream-merge: NA
- date: 20 Nov 2020
  version: "0.5.0"
  upstream-merge: NA
- date: 05 Nov 2020
  version: "0.4.0"
  upstream-merge: NA
- date: 25 Sep 2020
  version: "0.3.0"
  upstream-merge: NA
- date: 11 Aug 2020
  version: "0.2.0"
  upstream-merge: NA
- date: 03 Apr 2020
  version: "0.1.0"
  upstream-merge: NA
- date: 05 Mar 2020
  version: "0.0.1"
  upstream-merge: NA
