apiVersion: serving.kserve.io/v1alpha1
kind: ClusterServingRuntime
metadata:
  name: nvidia-nim-nv-rerankqa-llama
  namespace: default
spec:
  containers:
    - env:
        - name: NIM_CACHE_PATH
          value: /tmp
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              name: nvidia-nim-secrets
              key: NGC_API_KEY
      image: upmdev.azurecr.io/nim/nvidia/llama-3.2-nv-rerankqa-1b-v2:latest
      name: kserve-container
      ports:
        - containerPort: 8000
          protocol: TCP
      resources:
        limits:
          cpu: "4"
          memory: 12Gi
        requests:
          cpu: "4"
          memory: 12Gi
      volumeMounts:
        - mountPath: /dev/shm
          name: dshm
  imagePullSecrets:
    - name: edb-cred
  protocolVersions:
    - v2
    - grpc-v2
  supportedModelFormats:
    - autoSelect: true
      name: nvidia-nim-nv-rerankqa-llama
      priority: 1
      version: "latest"
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 20Gi
      name: dshm
