@startuml
left to right direction
rectangle "EDB Cloud" as src {


  rectangle "EDB Cloud Clusters" as edbclusters {
   database "PG Cluster" as edbcl1
   database "EPAS Cluster" as edbcl2

  }

  rectangle "EDB Cloud Users" {
    (Tom:{reader})
    (Jerry:{owner})
    (Louis:{})

  }

  [EDB Cloud org: acmebank-com] as org

}

rectangle Azure as tgt {

  rectangle "Azure AD" {
      (Tom:member)
      (Jerry:member)
      (Louis:member)

    }

  rectangle "k8s Clusters" as azureclusters {
    rectangle "us-east" as k1 {
     database "PG Cluster" as azuredbcl1

    }
    rectangle "japan-west" as k2 {
     database "EPAS Cluster" as azuredbcl2
    }
  }
  [Azure AD tenant:: acmebank.com] as AD

  (Jerry:member) -> azureclusters: owns
}

src -[hidden]d-> tgt
azureclusters -[hidden]u-> edbclusters
org  <->  AD: "1:1"
(Tom:{reader}) <- (Tom:member)
(Jerry:{owner})<- (Jerry:member)
(Louis:{})  <-  (Louis:member)


edbcl1 <- azuredbcl1
edbcl2 <- azuredbcl2
@enduml
