# Vagrantfile
etcd_nodes = 3 # nb of etcd nodes to create
patroni_nodes = 2 # nb of pg/patroni nodes to create

Vagrant.configure(2) do |config|
    config.vm.box = "debian/buster64"
    config.vm.provider 'libvirt' do |lv|
        lv.cpus = 1
        lv.memory = 1024
        lv.default_prefix = 'debian10'
    end
    config.vm.synced_folder ".", "/vagrant", disabled: true

    (1..etcd_nodes).each do |i|
        config.vm.define "etcd#{i}" do |etcd|
            etcd.vm.hostname = "etcd#{i}"
        end  
    end

    (1..patroni_nodes).each do |i|
        config.vm.define "pg-patroni#{i}" do |patroni|
            patroni.vm.hostname = "pg-patroni#{i}"
        end
    end

    config.vm.provision "shell", inline: <<-SHELL
        #-----------------------------------------------------------------------------------------------------------------------
        sudo apt-get update
        sudo apt-get install -y curl locales-all
        #-----------------------------------------------------------------------------------------------------------------------
    SHELL
end
