# yaml-language-server: $schema=https://raw.githubusercontent.com/EnterpriseDB/docs/refs/heads/develop/tools/automation/generators/relgen/meta-schema.json

product: EDB Postgres Distributed
shortname: pgd
title: EDB Postgres Distributed 5 release notes
description: Release notes for EDB Postgres Distributed 5 and later
intro: |
  The EDB Postgres Distributed documentation describes the latest version of EDB Postgres Distributed 5, including minor releases and patches. The release notes provide information on what was new in each release. For new functionality introduced in a minor or patch release, the content also indicates the release that introduced the feature.
columns:
- 0:
  label: Release Date
  key: shortdate
- 1:
  label: "EDB Postgres Distributed"
  key: version-link
- 2:
  label: "BDR extension"
  key: "$BDR"
- 3:
  label: "PGD CLI"
  key: "$PGD CLI"
- 4:
  label: "PGD Proxy"
  key: "$PGD Proxy"
components: [ "BDR", "PGD CLI", "PGD Proxy", "Utilities" ]
precursor:
- date: 31 May 2024
  version: "5.5.1"  
  "BDR": "5.5.1"
  "PGD CLI": 5.5.0
  "PGD Proxy": 5.5.0
- date: 16 May 2024
  version: "5.5.0"
  "BDR": 5.5.0
  "PGD CLI": 5.5.0
  "PGD Proxy": 5.5.0
- date: 03 April 2024
  version: "5.4.1"
  "BDR": 5.4.1
  "PGD CLI": 5.4.0
  "PGD Proxy": 5.4.0
- date: 05 March 2024
  version: "5.4.0"
  "BDR": 5.4.0
  "PGD CLI": 5.4.0
  "PGD Proxy": 5.4.0
- date: 14 November 2023
  version: "5.3.0"
  "BDR": 5.3.0
  "PGD CLI": 5.3.0
  "PGD Proxy": 5.3.0
- date: 04 August 2023
  version: "5.2.0"
  "BDR": 5.2.0
  "PGD CLI": 5.2.0
  "PGD Proxy": 5.2.0
- date: 16 May 2023
  version: "5.1.0"
  "BDR": 5.1.0
  "PGD CLI": 5.1.0
  "PGD Proxy": 5.1.0
- date: 21 Mar 2023
  version: "5.0.1"
  "BDR": 5.0.0
  "PGD CLI": 5.0.1
  "PGD Proxy": 5.0.1
- date: 21 Feb 2023
  version: "5.0.0"
  "BDR": 5.0.0
  "PGD CLI": 5.0.0
  "PGD Proxy": 5.0.0

  