apiVersion: pgd.k8s.enterprisedb.io/v1beta1
kind: PGDGroup
metadata:
  name: group-example-service-template
spec:
  instances: 3
  proxyInstances: 2
  pgd:
    parentGroup:
      create: true
      name: world
    proxySettings:
      enableReadNodeRouting: true
  inheritedMetadata:
    labels:
      region: zeta
    annotations:
      region.domain.com: region-domain
  cnp:
    storage:
      size: 1Gi
  connectivity:
    dns:
      # Change the domain when your service could be discovered in a different domain
      # domain: svc.cluster.local
      additional:
        - domain: alternate.domain
          hostSuffix: -dc1
    tls:
      mode: verify-ca
      clientCert:
        caCertSecret: client-ca-key-pair
        certManager:
          spec:
            issuerRef:
              name: client-ca-issuer
              kind: Issuer
              group: cert-manager.io
      serverCert:
        caCertSecret: server-ca-key-pair
        certManager:
          spec:
            issuerRef:
              name: server-ca-issuer
              kind: Issuer
              group: cert-manager.io
    groupServiceTemplate:
      metadata:
        labels:
          external-dns.alpha.kubernetes.io/hostname: '{group_fqdn}'
        annotations:
          group_service_name: '{group_svc}'
          group_service_fqdn: '{group_fqdn}'
      spec:
        type: ClusterIP
        clusterIP: None
      updateStrategy: replace
    nodeServiceTemplate:
      metadata:
        labels:
          application: test-node
        annotations:
          node_service_name: '{node_svc}'
          node_service_fqdn: '{node_fqdn}'
      spec:
        type: ClusterIP
        clusterIP: None
      updateStrategy: replace
    proxyReadServiceTemplate:
      metadata:
        labels:
          application: test-read-proxy
        annotations:
          read_proxy_service_name: '{proxy_svc}'
          read_proxy_service_fqdn: '{proxy_fqdn}'
      spec:
        type: ClusterIP
      updateStrategy: patch
    proxyServiceTemplate:
      metadata:
        labels:
          application: test-proxy
        annotations:
          proxy_service_name: '{proxy_svc}'
          proxy_service_fqdn: '{proxy_fqdn}'
      spec:
        type: NodePort
      updateStrategy: patch
