apiVersion: pgd.k8s.enterprisedb.io/v1beta1
kind: ImageCatalog
metadata:
  name: postgresql-pgd-catalog
spec:
  pgdImages:
  - image: docker.enterprisedb.com/k8s/postgresql-pgd:15-pgd5-ubi9
    major: 15
  - image: docker.enterprisedb.com/k8s/postgresql-pgd:16-pgd5-ubi9
    major: 16
  - image: docker.enterprisedb.com/k8s/postgresql-pgd:17-pgd5-ubi9
    major: 17
  proxyImage: docker.enterprisedb.com/k8s/edb-pgd-proxy:5.9.0-ubi9
---
apiVersion: pgd.k8s.enterprisedb.io/v1beta1
kind: PGDGroup
metadata:
  name: group-example-catalog
spec:
  instances: 2
  proxyInstances: 2
  witnessInstances: 1
  imageCatalogRef:
    apiGroup: pgd.k8s.enterprisedb.io
    kind: ImageCatalog
    major: 16
    name: postgresql-pgd-catalog
  imagePullSecrets:
  - name: registry-pullsecret
  pgd:
    parentGroup:
      name: world
      create: true
  cnp:
    storage:
      size: 1Gi
  connectivity:
    dns:
      additional:
        - domain: alternate.domain
        - domain: my.domain
          hostSuffix: -dc1
    tls:
      mode: verify-ca
      clientCert:
        caCertSecret: client-ca-key-pair
        certManager:
          spec:
            issuerRef:
              name: client-ca-issuer
              kind: Issuer
              group: cert-manager.io
      serverCert:
        caCertSecret: server-ca-key-pair
        certManager:
          spec:
            issuerRef:
              name: server-ca-issuer
              kind: Issuer
              group: cert-manager.io
