product: Postgres Enterprise Manager
shortname: pem
title: Postgres Enterprise Manager release notes
description: Release notes for Postgres Enterprise Manager 10.0 and later
columns:
- 0:
  label: "Postgres Enterprise Manager version"
  key: version-link
- 1:
  label: Release Date
  key: shortdate
intro: |
  The Postgres Enterprise Manager documentation describes the latest version of Postgres Enterprise Manager 10.
precursor:
- version: "10.1.0"
  date: 15 May 2025
- version: "10.0.0"
  date: 24 Mar 2025