exec(open('scripts/add_frontmatter.py').read())
exec(open('scripts/sort_toc_nested.py').read())
exec(open('scripts/fix_image_links.py').read())
exec(open('scripts/internal_links.py').read())
exec(open('scripts/substitutions.py').read())
