# Vagrantfile
etcd_nodes = 3 # nb of etcd nodes to create
patroni_nodes = 2 # nb of pg/patroni nodes to create

Vagrant.configure(2) do |config|
    config.vm.box = "debian/bullseye64"
    config.vm.provider 'libvirt' do |lv|
        lv.cpus = 1
        lv.memory = 1024
        lv.default_prefix = 'debian11'
        # lv.machine_virtual_size = 30
    end
    config.vm.synced_folder ".", "/vagrant", disabled: true

    (1..etcd_nodes).each do |i|
        config.vm.define "etcd#{i}" do |etcd|
            etcd.vm.hostname = "etcd#{i}"
        end  
    end

    (1..patroni_nodes).each do |i|
        config.vm.define "epas-patroni#{i}" do |patroni|
            patroni.vm.hostname = "epas-patroni#{i}"
        end
    end

    (1..patroni_nodes).each do |i|
        config.vm.define "pgext-patroni#{i}" do |patroni|
            patroni.vm.hostname = "pgext-patroni#{i}"
        end
    end

    config.vm.provision "shell", inline: <<-SHELL
        #-----------------------------------------------------------------------------------------------------------------------
        sudo apt-get update
        sudo apt-get install -y curl locales-all
        # sudo resize2fs /dev/vda1
        #-----------------------------------------------------------------------------------------------------------------------
    SHELL
end
