apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: cluster-example
  annotations:
    "k8s.enterprisedb.io/addons": '["external-backup-adapter-cluster"]'
    "k8s.enterprisedb.io/externalBackupAdapterClusterConfig": |-
      electedResourcesDecorators:
        - key: "test/edb-elected"
          metadataType: "label"
          value: "true"
      excludedResourcesDecorators:
        - key: "test/ignore"
          metadataType: "label"
          value: "true"
      backupInstanceDecorators:
        - key: "test/hooks"
          metadataType: "label"
          value: "true"
      preBackupHookConfiguration:
        container:
          key: "test/pre-backup-container"
        command:
          key: "test/pre-backup-command"
        onError:
          key: "test/pre-backup-on-error"
      postBackupHookConfiguration:
        container:
          key: "test/post-backup-container"
        command:
          key: "test/post-backup-command"
spec:
  instances: 3
  storage:
    size: 1Gi
