name: 'Update PR Description'
description: 'Adds a message to the end of a PR description'
runs:
  using: 'node20'
  main: 'dist/index.js'
inputs:
  message:
    description: 'The message to append'
    required: true
  github-token:
    description: 'Token with write access to the PR'
    required: true
  repo: 
    description: 'The repository to update the PR in'
    required: true
  repo-owner:
    description: 'The owner of the repository to update the PR in'
    required: true
  pr-number:
    description: 'The PR number to update'
    required: true