# yaml-language-server: $schema=https://raw.githubusercontent.com/EnterpriseDB/docs/refs/heads/develop/tools/automation/generators/relgen/meta-schema.json

product: EDB Postgres Distributed
shortname: pgd
title: EDB Postgres Distributed 4 release notes
description: Release notes for EDB Postgres Distributed 5 and later
intro: |
  The EDB Postgres Distributed documentation describes the latest version of EDB Postgres Distributed 4, including minor releases and patches. The release notes provide information on what was new in each release. For new functionality introduced in a minor or patch release, the content also indicates the release that introduced the feature.

  !!! Note About version numbers
  PGD Version 4 takes its version number from the BDR version bundled with the release. Where HARP, TPA or the CLI have been updated without a change in BDR version, that new package is shown as +p1 or +p2 and so on appended to the version number.
  !!!
#
# Support needed for: TODO
# redirects:
# - /harp/latest/01_release_notes/
# - /harp/latest/01_release_notes/harp2.0.3_rel_notes/
#
columns:
- 0:
  label: Release Date
  key: shortdate
- 1:
  label: "EDB Postgres Distributed"
  key: version-link
- 2:
  label: "BDR"
  key: "$BDR"
- 3:
  label: "HARP"
  key: "$HARP"
- 4:
  label: "CLI"
  key: "$CLI"
- 5:
  label: "TPAexec"
  key: "$TPAexec"
components: [ "BDR", "HARP", "CLI", "TPAexec" ]
precursor:
- date: 16 May 2024
  version: "4.3.5"
  "BDR": "4.3.4"
  "HARP": "2.4.1"
  "CLI": "1.1.2"
  "TPAexec": "[23.32](/tpa/latest/rel_notes/tpa_23.32)"
- date: 05 Mar 2024
  version: "4.3.4"
  "BDR": "4.3.4"
  "HARP": "2.4"
  "CLI": "1.1.2"
  "TPAexec": "[23.29](/tpa/latest/rel_notes/tpa_23.29)"
- date: 14 Nov 2023
  version: "4.3.3"
  "BDR": "4.3.3"
  "HARP": "2.3.2"
  "CLI": "1.1.2"
  "TPAexec": "[23.24](/tpa/latest/rel_notes/tpa_23.24)"
- date: 17 Oct 2023
  version: "4.3.2+p1"
  "BDR": "4.3.2"
  "HARP": "2.3.2"
  "CLI": "1.1.1"
  "TPAexec": "[23.20](/tpa/latest/rel_notes/tpa_23.20)"
- date: 31 Aug 2023
  version: "4.3.2"
  "BDR": "4.3.2"
  "HARP": "2.3.1"
  "CLI": "1.1.1"
  "TPAexec": "[23.20](/tpa/latest/rel_notes/tpa_23.20)"
- date: 27 Jul 2023
  version: "4.3.1+p2"
  "BDR": "4.3.1"
  "HARP": "2.3.1"
  "CLI": "1.1.1"
  "TPAexec": "[23.19](/tpa/latest/rel_notes/tpa_23.19)"
- date: 12 Jul 2023
  version: "4.3.1+p1"
  "BDR": "4.3.1"
  "HARP": "2.3.0"
  "CLI": "1.1.1"
  "TPAexec": "[23.19](/tpa/latest/rel_notes/tpa_23.19)"
- date: 17 May 2023
  version: "4.3.1"
  "BDR": "4.3.1"
  "HARP": "2.2.3"
  "CLI": "1.1.1"
  "TPAexec": "[23.17](/tpa/latest/rel_notes/tpa_23.17)"
- date: 30 Mar 2023
  version: "4.3.0+p1"
  "BDR": "4.3.0"
  "HARP": "2.2.2"
  "CLI": "1.1.0"
  "TPAexec": "[23.9](/tpa/latest/rel_notes/tpa_23.1-11#tpa-239)"
- date: 14 Feb 2023 
  version: "4.3.0"
  "BDR": "4.3.0"
  "HARP": "2.2.1"
  "CLI": "1.1.0"
  "TPAexec": "[23.9](/tpa/latest/rel_notes/tpa_23.1-11#tpa-239)"
- date: 14 Dec 2022   
  version: "4.2.2"
  "BDR": "4.2.2"
  "HARP": "2.2.1"
  "CLI": "1.1.0"
  "TPAexec": "[23.9](/tpa/latest/rel_notes/tpa_23.1-11#tpa-239)"
- date: 16 Nov 2022   
  version: "4.2.1"
  "BDR": "4.2.1"
  "HARP": "2.2.1"
  "CLI": "1.1.0"
  "TPAexec": "[23.7](/tpa/latest/rel_notes/tpa_23.1-11#tpa-237)"
- date: 22 Aug 2022
  version: "4.2.0"
  "BDR": "4.2.0"
  "HARP": "2.2.0"
  "CLI": "1.1.0"
  "TPAexec": "[23.5](/tpa/latest/rel_notes/tpa_23.1-11#tpa-235)"
- date: 21 Jun 2022
  version: "4.1.1"
  "BDR": "4.1.1"
  "HARP": "2.1.1"
  "CLI": "1.0.0"
  "TPAexec": "[23.2](/tpa/latest/rel_notes/tpa_23.1-11#tpa-232)"
- date: 17 May 2022
  version: "4.1.0"
  "BDR": "4.1.0"
  "HARP": "2.1.0"
  "CLI": "1.0.0"
  "TPAexec": "[23.1](/tpa/latest/rel_notes/tpa_23.1-11#tpa-231)"
- date: 31 Mar 2022
  version: "4.0.3"
  "BDR": "-"
  "HARP": "2.0.3"
  "CLI": "-"
  "TPAexec": "22.10"
- date: 24 Feb 2022
  version: "4.0.2"
  "BDR": "4.0.2"
  "HARP": "2.0.2"
  "CLI": "-"
  "TPAexec": "22.9"
- date: 31 Jan 2022
  version: "4.0.1"
  "BDR": "4.0.1"
  "HARP": "2.0.1"
  "CLI": "-"
  "TPAexec": "22.6"
- date: 01 Dec 2021
  version: "4.0.0"
  "BDR": "4.0.0"
  "HARP": "2.0.0"
  "CLI": "-"
  "TPAexec": "21.9"



# | Release Date | EDB Postgres Distributed            | BDR   | HARP  | CLI   | TPAexec                                                      |
# |--------------|-------------------------------------|-------|-------|-------|--------------------------------------------------------------|
# | 15 Oct 2024  | [4.3.6](pgd_4.3.6_rel_notes)        | 4.3.6 | 2.4.2 | 1.1.2 | [23.34.1](/tpa/latest/rel_notes/tpa_23.34.1_rel_notes/)           |
# | 16 May 2024  | [4.3.5](pgd_4.3.5_rel_notes)        | 4.3.4 | 2.4.1 | 1.1.2 | [23.32](/tpa/latest/rel_notes/tpa_23.32_rel_notes/)           |
# | 05 Mar 2024  | [4.3.4](pgd_4.3.4_rel_notes)        | 4.3.4 | 2.4   | 1.1.2 | [23.29](/tpa/latest/rel_notes/tpa_23.29_rel_notes/)           |
# | 14 Nov 2023  | [4.3.3](pgd_4.3.3_rel_notes)        | 4.3.3 | 2.3.2 | 1.1.2 | [23.24](/tpa/latest/rel_notes/tpa_23.24_rel_notes)           |
# | 17 Oct 2023  | [4.3.2+p1](pgd_4.3.2+p1_rel_notes)  | 4.3.2 | 2.3.2 | 1.1.1 | [23.20](/tpa/latest/rel_notes/tpa_23.20_rel_notes)           |
# | 31 Aug 2023  | [4.3.2 ](pgd_4.3.2_rel_notes)       | 4.3.2 | 2.3.1 | 1.1.1 | [23.20](/tpa/latest/rel_notes/tpa_23.20_rel_notes)           |
# | 27 Jul 2023  | [4.3.1+p2 ](pgd_4.3.1+p2_rel_notes) | 4.3.1 | 2.3.1 | 1.1.1 | [23.19](/tpa/latest/rel_notes/tpa_23.19_rel_notes)           |
# | 12 Jul 2023  | [4.3.1+p1 ](pgd_4.3.1+p1_rel_notes) | 4.3.1 | 2.3.0 | 1.1.1 | [23.19](/tpa/latest/rel_notes/tpa_23.19_rel_notes)           |
# | 17 May 2023  | [4.3.1](pgd_4.3.1_rel_notes)        | 4.3.1 | 2.2.3 | 1.1.1 | [23.17](/tpa/latest/rel_notes/tpa_23.17_rel_notes)           |
# | 30 Mar 2023  | [4.3.0+p1](pgd_4.3.0+p1_rel_notes)  | 4.3.0 | 2.2.2 | 1.1.0 | [23.9](/tpa/latest/rel_notes/tpa_23.1-11_rel_notes/#tpa-239) |
# | 14 Feb 2023  | [4.3.0](pgd_4.3.0_rel_notes)        | 4.3.0 | 2.2.1 | 1.1.0 | [23.9](/tpa/latest/rel_notes/tpa_23.1-11_rel_notes/#tpa-239) |
# | 14 Dec 2022  | [4.2.2](pgd_4.2.2_rel_notes)        | 4.2.2 | 2.2.1 | 1.1.0 | [23.9](/tpa/latest/rel_notes/tpa_23.1-11_rel_notes/#tpa-239) |
# | 16 Nov 2022  | [4.2.1](pgd_4.2.1_rel_notes)        | 4.2.1 | 2.2.1 | 1.1.0 | [23.7](/tpa/latest/rel_notes/tpa_23.1-11_rel_notes/#tpa-237) |
# | 22 Aug 2022  | [4.2.0](pgd_4.2.0_rel_notes)        | 4.2.0 | 2.2.0 | 1.1.0 | [23.5](/tpa/latest/rel_notes/tpa_23.1-11_rel_notes/#tpa-235) |
# | 21 Jun 2022  | [4.1.1](pgd_4.1.1_rel_notes)        | 4.1.1 | 2.1.1 | 1.0.0 | [23.2](/tpa/latest/rel_notes/tpa_23.1-11_rel_notes/#tpa-232) |
# | 17 May 2022  | [4.1.0](pgd_4.1.0_rel_notes)        | 4.1.0 | 2.1.0 | 1.0.0 | [23.1](/tpa/latest/rel_notes/tpa_23.1-11_rel_notes/#tpa-231) |
# | 31 Mar 2022  | [4.0.3](pgd_4.0.3_rel_notes)        | -     | 2.0.3 | -     | 22.10                                                        |
# | 24 Feb 2022  | [4.0.2](pgd_4.0.2_rel_notes)        | 4.0.2 | 2.0.2 | -     | 22.9                                                         |
# | 31 Jan 2022  | [4.0.1](pgd_4.0.1_rel_notes)        | 4.0.1 | 2.0.1 | -     | 22.6                                                         |
# | 01 Dec 2021  | [4.0.0](pgd_4.0.0_rel_notes)        | 4.0.0 | 2.0.0 | -     | 21.9                                                         |
