# yaml-language-server: $schema=https://raw.githubusercontent.com/EnterpriseDB/docs/refs/heads/develop/tools/automation/generators/relgen/meta-schema.json

product: Advanced Storage Pack
shortname: asp
title: Advanced Storage Pack release notes
description: Release notes for Advanced Storage Packr
intro: |
  The Advanced Storage Pack documentation describes the latest version of Advanced Storage Pack, including minor releases and patches.
  These release notes cover what was new in each release. 
  For new functionality introduced in a minor or patch release, there are also indicators in the content about the release that introduced the feature.
columns:
- 0:
  label: "Version"
  key: version-link
- 1:
  label: Release Date
  key: shortdate
precursor:
- date: 09 Nov 2023
  version: "1.2.1"  
- date: 30 Nov 2022
  version: "1.0.0"
