name: check links on PR
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          lfs: true
          ref: ${{ github.event.pull_request.head.sha }}
      
      - name: setup node
        uses: actions/setup-node@v4

      - name: install dependencies
        run: npm --prefix ./tools/automation/actions/link-check ci

      - name: check links
        uses: ./tools/automation/actions/link-check
