name: Deploy build to Netlify
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      enable-pull-request-comment: 
        description: whether to comment on the triggering PR
        required: false
        default: true
        type: boolean
      enable-commit-comment: 
        description: whether to comment on the triggering commit
        required: false
        default: true
        type: boolean
      alias: 
        description: name for the deployment (used to set custom / stable Netlify url)
        required: false
        type: string
  
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull build artifacts
        uses: actions/download-artifact@v4
        with: 
          path: ./public
          merge-multiple: true

      - name: list
        run: ls -lfR ./public

      - name: Deploy to Netlify
        id: netlify-deploy
        uses: nwtgck/actions-netlify@v3
        with:
          publish-dir: "./public"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          enable-pull-request-comment: ${{ inputs.enable-pull-request-comment }}
          enable-commit-comment: ${{ inputs.enable-commit-comment }}
          alias: ${{ inputs.alias }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEVELOP_SITE_ID }}
