name: Deploy build to Netlify
on:
  workflow_dispatch:
  workflow_call:
    inputs:
      sha:
        description: git hash of ref that was built
        required: true
        type: string
      pages-cache-key:
        description: key for pages cache
        required: true
        type: string
      pdf-cache-key:
        description: key for pdf cache
        required: false
        type: string
      enable-pull-request-comment: 
        description: whether to comment on the triggering PR
        required: false
        default: true
        type: boolean
      enable-commit-comment: 
        description: whether to comment on the triggering commit
        required: false
        default: true
        type: boolean
      alias: 
        description: name for the deployment (used to set custom / stable Netlify url)
        required: false
        type: string
      production:
        description: whether to mark this deployment as the current production deploy for the site
        required: false
        default: false
        type: boolean
    secrets:
      NETLIFY_SITE_ID:
        description: Netlify site ID to deploy to
        required: true
      NETLIFY_AUTH_TOKEN:
        required: true
    outputs:
      deploy-url:
        description: netlify deployment URL
        value: ${{ jobs.deploy.outputs.deploy-url }}

jobs:
  deploy:
    runs-on: docs-16c-64gb-600gb
    outputs:
      deploy-url: ${{ steps.netlify-deploy.outputs.NETLIFY_URL }}
    steps:
      - name: Checkout netlify directory
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.sha }}
          sparse-checkout: |
            /netlify
          sparse-checkout-cone-mode: false

      - name: Pull pages cache
        uses: actions/cache/restore@v4
        with:
          fail-on-cache-miss: true
          path: |
            public/*
            !public/pdfs
            .cache
          key: ${{ inputs.pages-cache-key }}

      - name: Pull PDF cache
        if: ${{ inputs.pdf-cache-key }}
        uses: actions/cache/restore@v4
        with:
          path: |
            product_docs/**/*.pdf
            product_docs/**/*.pdf-hash
            advocacy_docs/**/*.pdf
            advocacy_docs/**/*.pdf-hash
          key: ${{ inputs.pdf-cache-key }}

      - name: Copy pdfs to build output
        run: |
          mkdir -p public/pdfs
          rsync -avm --filter="+ */" --filter="-! *.pdf" advocacy_docs/ public/pdfs/ || :
          rsync -avm --filter="+ */" --filter="-! *.pdf" product_docs/docs/ public/pdfs/ || :

      - name: Copy lib to netlify edge functions
        run: |
          mkdir -p netlify/edge-functions/lib
          cp -R public/lib/* netlify/edge-functions/lib/

      - name: Install Deno
        uses: denoland/setup-deno@v2

      - name: Install Netlify CLI
        run: |
          npm install -g netlify-cli
            
      - name: Deploy to Netlify
        id: netlify-deploy
        # adapted from https://github.com/netlify/actions/blob/master/cli/entrypoint.sh
        run: |
            netlify deploy --dir=./public ${{!inputs.production && format('--alias={0}', inputs.alias) || ''}} ${{ inputs.production && '--prod' || ''}} | tee output.txt

            NETLIFY_OUTPUT=$(cat output.txt)
            NETLIFY_URL=$(grep -Eo '(http|https)://[a-zA-Z0-9./?=_-]*(--)[a-zA-Z0-9./?=_-]*' output.txt) 
            NETLIFY_LOGS_URL=$(grep -Eo '(http|https)://app.netlify.com/[a-zA-Z0-9./?=_-]*' output.txt)
            NETLIFY_LIVE_URL=$(grep -Eo '(http|https)://[a-zA-Z0-9./?=_-]*' output.txt | grep -Eov "netlify.com")

            echo "NETLIFY_OUTPUT<<EOF" >> "$GITHUB_OUTPUT"
            echo "$NETLIFY_OUTPUT" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"
            echo "NETLIFY_URL=$NETLIFY_URL" >> "$GITHUB_OUTPUT"
            echo "NETLIFY_LOGS_URL<<EOF" >> "$GITHUB_OUTPUT"
            echo "$NETLIFY_LOGS_URL" >> "$GITHUB_OUTPUT"
            echo "EOF" >> "$GITHUB_OUTPUT"
            echo "NETLIFY_LIVE_URL=$NETLIFY_LIVE_URL" >> "$GITHUB_OUTPUT"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
