name: sync CNP repo
on:
  repository_dispatch:
    types: [sync_files]
jobs:
  sync-repo:
    env:
      # The body text of the PR requests that will be created
      PR_BODY: Automated changes to pull in docs changes from ${{ github.event.client_payload.repo }} repo

      # The name of the branch that will be created
      PR_BRANCH_NAME: ${{ github.workflow }}_${{ github.run_id }}

      # The title of the PR request that will be created
      PR_TITLE: Automated changes from ${{ github.event.client_payload.repo }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout destination
        uses: actions/checkout@v2
        with:
          path: destination

      - name: Checkout source repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.client_payload.repo }}
          token: ${{ secrets.GH_TOKEN }}
          path: source

      # Begin file processing steps
      - name: setup node for file processor
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: install file processor dependencies
        run: npm install production
        working-directory: destination/.github/fileProcessor

      - name: Run file processor
        run: |
          case ${{ github.event.client_payload.repo }} in

            jaek-s/cloud-native-postgresql)
              cd docs

              node ../destination/scripts/fileProcessor/main.mjs \
                      -f "src/**/quickstart.md" \
                      -p cnp/add-quickstart-content

              node ../destination/scripts/fileProcessor/main.mjs \
                -f "src/**/*.md" \
                -p "cnp/update-yaml-links" \
                -p "cnp/add-frontmatters" \
                -p "cnp/rename-to-mdx"

              cp -f src/* ../../destination/advocacy_docs/kubernetes/
              ;;


            *)
              echo "The workflow has not been configured for the  ${{ github.event.client_payload.repo }} repo"
              ;;
          esac
        working-directory: source

      # End file processing steps

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3.10.0
        with:
          body: ${{ env.PR_BODY }}
          branch: ${{ env.PR_BRANCH_NAME }}
          path: destination/
          title: ${{ env.PR_TITLE }}
