name: Trigger Deploy of Docs on Push
on:
  push:
    branches:
      - master
jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch to Docs Staging
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_DOCS_ACCESS_TOKEN }}
          repository: rocketinsights/edb_docs
          event-type: advo-deploy-develop
      - name: Repository Dispatch to Docs Production
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_DOCS_ACCESS_TOKEN }}
          repository: rocketinsights/edb_docs
          event-type: advo-deploy-prod
